xml_mgmt_port: 5550
rest_mgmt_port: 5554
peer_group:
  - fqdn: pr-apic-dpgw1.nsb.local
    ip: 172.22.10.139
  - fqdn: pr-apic-dpgw2.nsb.local
    ip: 172.22.10.140
  - fqdn: pr-apic-dpgw3.nsb.local
    ip: 172.22.10.141
host_aliases:
  - fqdn: pr-apic-mgr.nsb.local
    ip: &mgr_ip 192.168.72.11
  - fqdn: platform-api.pr-apic-mgr.nsb.local
    ip: *mgr_ip
  - fqdn: consumer-api.pr-apic-mgr.nsb.local
    ip: *mgr_ip
  - fqdn: cloud-admin-ui.pr-apic-mgr.nsb.local
    ip: *mgr_ip
  - fqdn: api-manager-ui.pr-apic-mgr.nsb.local
    ip: *mgr_ip
  - fqdn: hub.pr-apic-mgr.nsb.local
    ip: *mgr_ip
  - fqdn: turnstile.pr-apic-mgr.nsb.local
    ip: *mgr_ip

  - fqdn: pr-apic-anytcs.nsb.local
    ip: &anytcs_ip 192.168.72.12
  - fqdn: analytics-client.pr-apic-anytcs.nsb.local
    ip: *anytcs_ip
  - fqdn: analytics-ingestion.pr-apic-anytcs.nsb.local
    ip: *anytcs_ip

  - fqdn: pr-apic-devptl.nsb.local
    ip: &devptl_ip 192.168.72.13
  - fqdn: portal-admin.pr-apic-devptl.nsb.local
    ip: *devptl_ip
  - fqdn: portal-www.pr-apic-devptl.nsb.local
    ip: *devptl_ip
