xml_mgmt_port: 5550
rest_mgmt_port: 5554
peer_group:
  - fqdn: dr-apic-dpgw1.apic.nsb.local
    ip: 192.168.173.139
  - fqdn: dr-apic-dpgw2.apic.nsb.local
    ip: 192.168.173.140
  - fqdn: dr-apic-dpgw3.apic.nsb.local
    ip: 192.168.173.141
host_aliases: []
